# Default values for devspaces-config-job
namespace: openshift-devspaces

image:
  repository: quay.io/agnosticd/ee-multicloud
  tag: latest

gitops:
  repoUrl: "https://github.com/rh-opencodequest/gitops.git"
  branch: "main"

