# Default values for rhdh-config-job
# Cluster name - change this to configure different clusters
# Options: atlantis, central, gotham, madripoor, metropolis, wakanda
cluster: atlantis

namespace: backstage

image:
  repository: quay.io/agnosticd/ee-multicloud
  tag: latest

gitlab:
  namespace: gitlab

gitops:
  repoUrl: "https://github.com/rh-opencodequest/gitops.git"
  branch: "main"

